# Generated by Django 5.0.14 on 2026-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_stops',
            field=models.PositiveIntegerField(default=0, help_text='Number of intermediate stops.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, help_text='Scheduled return date for round-trip bookings.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, help_text='Scheduled return time for round-trip bookings.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='round_trip',
            field=models.BooleanField(default=False, help_text='Whether the booking includes a return leg.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stop_addresses',
            field=models.TextField(blank=True, default='', help_text='Descriptions / addresses of intermediate stops.'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='service_type',
            field=models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('point_to_point', 'Point-to-Point'), ('hourly', 'Hourly Service')], default='airport_transfer', help_text='Type of service this pricing rule applies to.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dispatch_email',
            field=models.EmailField(blank=True, default='dispatch@aeroluxeselect.com', help_text='Recipient email address for dispatch alerts.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_api_key',
            field=models.CharField(blank=True, default='', help_text='API key for SendGrid / Resend / Mailgun.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_domain',
            field=models.CharField(blank=True, default='', help_text='API Domain for Mailgun / Resend (e.g. mg.yourdomain.com).', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_from',
            field=models.EmailField(blank=True, default='no-reply@aeroluxeselect.com', help_text='From email address for confirmations.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, default='', help_text='SMTP Host (e.g. smtp.gmail.com).', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_password',
            field=models.CharField(blank=True, default='', help_text='SMTP Password / API Key secret.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP Port (e.g. 587 or 465).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_provider',
            field=models.CharField(choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('RESEND', 'Resend'), ('MAILGUN', 'Mailgun')], default='SMTP', help_text='Third-party provider or SMTP for sending notifications.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for secure SMTP connection.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_username',
            field=models.CharField(blank=True, default='', help_text='SMTP Username / API User.', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('point_to_point', 'Point-to-Point'), ('hourly', 'Hourly Service')], default='airport_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='service_type',
            field=models.CharField(blank=True, choices=[('airport_transfer', 'Airport Transfer'), ('point_to_point', 'Point-to-Point'), ('hourly', 'Hourly Service')], default='', help_text='Which service this testimonial relates to.', max_length=20),
        ),
    ]
