# Generated by Django 5.0.14 on 2026-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_number_of_stops_booking_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transfer_direction',
            field=models.CharField(choices=[('AIRPORT_TO_DEST', 'Airport to Destination'), ('DEST_TO_AIRPORT', 'Destination to Airport')], default='AIRPORT_TO_DEST', help_text='Direction of travel for Airport Transfers.', max_length=20),
        ),
    ]
