# Generated by Django 5.0.14 on 2026-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_transfer_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_point',
            field=models.TextField(blank=True, default='', help_text='Specific instructions for chauffeur meeting point (e.g. Exit Gate B).'),
        ),
    ]
