# Generated by Django 5.0.14 on 2026-06-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_meeting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', help_text='Terms and conditions text displayed during checkout.'),
        ),
    ]
