# Generated by Django 5.0.14 on 2026-06-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('point_to_point', 'Point-to-Point'), ('hourly', 'Hourly Service'), ('luxury_rental', 'Luxury Rental')], default='airport_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='service_type',
            field=models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('point_to_point', 'Point-to-Point'), ('hourly', 'Hourly Service'), ('luxury_rental', 'Luxury Rental')], default='airport_transfer', help_text='Type of service this pricing rule applies to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='service_type',
            field=models.CharField(blank=True, choices=[('airport_transfer', 'Airport Transfer'), ('point_to_point', 'Point-to-Point'), ('hourly', 'Hourly Service'), ('luxury_rental', 'Luxury Rental')], default='', help_text='Which service this testimonial relates to.', max_length=20),
        ),
    ]
