# Generated by Django 5.0.14 on 2026-06-09 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_price_per_mile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='linked_booking',
            field=models.ForeignKey(blank=True, help_text='Reference to the linked leg of a round-trip booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='core.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of passengers for this ride.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='zone_name',
            field=models.CharField(blank=True, choices=[('hotel_zone', 'Hotel Zone'), ('city_center', 'City Center'), ('remote', 'Remote Area'), ('manhattan_downtown', 'Manhattan Downtown'), ('manhattan_midtown', 'Manhattan Midtown'), ('manhattan_uptown', 'Manhattan Uptown')], default='', help_text='Zone name for zone-based pricing (leave blank for destination-based).', max_length=30),
        ),
    ]
