# Generated by Django 5.0.14 on 2026-06-10 04:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_linked_booking_booking_passenger_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['site', 'service_type', 'base_price'], 'verbose_name': 'Pricing Rule', 'verbose_name_plural': 'Pricing Rules'},
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='surge_multiplier',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='zone_max_distance_km',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='zone_min_distance_km',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='zone_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Specific vehicle selected for this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='km_threshold',
            field=models.PositiveIntegerField(default=25, help_text='Distance threshold in km. Per-km pricing starts beyond this distance.'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='site',
            field=models.ForeignKey(default=1, help_text='Site this rule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='core.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Specific vehicle this price applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price in USD (hourly rate or P2P base fare).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='price_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per km for Point-to-Point (applied beyond km_threshold).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='service_type',
            field=models.CharField(choices=[('hourly', 'Hourly Service'), ('point_to_point', 'Point-to-Point')], default='hourly', help_text='Type of service (Hourly or Point-to-Point only).', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='vehicle_category',
            field=models.ForeignKey(help_text='Vehicle category (used as fallback if no vehicle-specific rule).', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='core.vehiclecategory'),
        ),
        migrations.CreateModel(
            name='ZoneVehiclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(help_text='Zone name (e.g. "Punta Cana Hotels", "Manhattan Midtown").', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Fixed price in USD for this airport→vehicle→zone combination.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(help_text='Airport for this pricing.', on_delete=django.db.models.deletion.CASCADE, related_name='zone_prices', to='core.airport')),
                ('vehicle', models.ForeignKey(help_text='Specific vehicle for this pricing.', on_delete=django.db.models.deletion.CASCADE, related_name='zone_prices', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Zone Vehicle Price',
                'verbose_name_plural': 'Zone Vehicle Prices',
                'ordering': ['airport', 'zone_name', 'vehicle'],
                'unique_together': {('airport', 'vehicle', 'zone_name')},
            },
        ),
    ]
