# Generated by Django 5.0.14 on 2026-06-11 19:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pricingrule_options_remove_pricingrule_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Maps API key for distance calculation and map routing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_provider',
            field=models.CharField(choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('RESEND', 'Resend'), ('MAILGUN', 'Mailgun'), ('BREVO', 'Brevo')], default='SMTP', help_text='Third-party provider or SMTP for sending notifications.', max_length=20),
        ),
        migrations.CreateModel(
            name='AirportCategoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in USD for this airport and category.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('base_km', models.PositiveIntegerField(default=25, help_text='Base distance in kilometers included in the base price.')),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Price per extra kilometer beyond the base distance.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(help_text='Airport for this pricing.', on_delete=django.db.models.deletion.CASCADE, related_name='category_prices', to='core.airport')),
                ('vehicle_category', models.ForeignKey(help_text='Vehicle category for this pricing.', on_delete=django.db.models.deletion.CASCADE, related_name='airport_prices', to='core.vehiclecategory')),
            ],
            options={
                'verbose_name': 'Airport Category Price',
                'verbose_name_plural': 'Airport Category Prices',
                'ordering': ['airport', 'vehicle_category'],
                'unique_together': {('airport', 'vehicle_category')},
            },
        ),
        migrations.DeleteModel(
            name='ZoneVehiclePrice',
        ),
    ]
