# Generated by Django 5.0.14 on 2026-06-12 01:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_google_maps_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons_return',
            field=models.ManyToManyField(blank=True, help_text='Add-ons selected specifically for the return leg.', related_name='return_bookings', to='core.premiumaddon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The amount currently paid by the customer.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_separately',
            field=models.BooleanField(default=False, help_text='Whether the customer requested to pay for outbound and return legs separately.'),
        ),
    ]
