# Generated by Django 5.0.14 on 2026-06-12 02:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking_addons_return_booking_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the 12-hour reminder email has been sent.'),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash on Delivery'), ('STRIPE', 'Stripe Card'), ('MANUAL', 'Manual Logged')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.booking')),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('processing', 'Booking Processing'), ('confirmed', 'Booking Confirmed'), ('reminder_12h', '12h Pickup Reminder'), ('cancelled', 'Booking Cancelled')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField(help_text='HTML template content. Placeholders: {customer_name}, {booking_reference}, {pickup_date}, {pickup_time}, {return_date}, {return_time}, {total_price}, {amount_paid}, {balance}, {pickup_address}, {dropoff_address}, {service_type}, {flight_number}')),
                ('text_content', models.TextField(help_text='Plain text template content. Placeholders same as HTML.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='core.site')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'unique_together': {('site', 'email_type')},
            },
        ),
    ]
