# Generated by Django 5.0.14 on 2026-06-12 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_booking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('processing', 'Booking Processing'), ('confirmed', 'Booking Confirmed'), ('reminder_12h', '12h Pickup Reminder'), ('cancelled', 'Booking Cancelled')], max_length=20)),
                ('message_content', models.TextField(help_text='WhatsApp message content. Placeholders: {customer_name}, {booking_reference}, {pickup_date}, {pickup_time}, {return_date}, {return_time}, {total_price}, {amount_paid}, {balance}, {pickup_address}, {dropoff_address}, {service_type}, {flight_number}')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='core.site')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'unique_together': {('site', 'trigger_type')},
            },
        ),
    ]
