# Generated by Django 5.0.14 on 2026-06-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_whatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_meeting_point',
            field=models.TextField(blank=True, default='', help_text='Specific instructions for return leg chauffeur meeting point.'),
        ),
    ]
