# Generated by Django 5.0.14 on 2026-06-15 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_booking_return_meeting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated distance in kilometers.', max_digits=8),
        ),
    ]
