# Generated by Django 5.0.14 on 2026-06-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_fix_airport_dest_accents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='vehicle',
        ),
    ]
