# Generated by Django 5.0.14 on 2026-06-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_booking_vehicle_remove_pricingrule_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
