# Generated by Django 5.0.14 on 2026-05-31 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la chambre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug (URL)')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Numéro de chambre')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par nuit (€)')),
                ('capacity', models.IntegerField(default=2, verbose_name='Capacité (Personnes)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Image de la chambre')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Wi-Fi Gratuit')),
                ('has_jacuzzi', models.BooleanField(default=False, verbose_name='Jacuzzi Privé')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcon / Terrasse')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Climatisation')),
                ('has_tv', models.BooleanField(default=True, verbose_name='TV Écran Plat')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='Minibar Premium')),
                ('has_room_service', models.BooleanField(default=False, verbose_name="Service d'étage 24/7")),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='SiteElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Clé unique')),
                ('label', models.CharField(max_length=100, verbose_name='Label éditeur')),
                ('value', models.TextField(verbose_name='Valeur textuelle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_elements/', verbose_name='Image associée')),
                ('category', models.CharField(choices=[('ACCUEIL', "Page d'Accueil"), ('ABOUT', "À Propos de l'Hôtel"), ('SERVICES', 'Nos Services & Charme'), ('CONTACT', 'Contact & Pied de Page')], default='ACCUEIL', max_length=20, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Élément du Site',
                'verbose_name_plural': 'Éléments du Site',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default="L'Horizon Impérial", max_length=100, verbose_name="Nom de l'Hôtel")),
                ('contact_email', models.EmailField(default='contact@horizon-imperial.com', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(default='+33 (0)4 93 00 00 00', max_length=20, verbose_name='Téléphone de contact')),
                ('address', models.CharField(default='12 Boulevard de la Croisette, 06400 Cannes, France', max_length=255, verbose_name='Adresse')),
                ('social_facebook', models.URLField(blank=True, default='https://facebook.com', verbose_name='Lien Facebook')),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com', verbose_name='Lien Instagram')),
                ('social_twitter', models.URLField(blank=True, default='https://twitter.com', verbose_name='Lien Twitter')),
            ],
            options={
                'verbose_name': 'Paramètres Généraux',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('check_in', models.DateField(verbose_name="Date d'arrivée")),
                ('check_out', models.DateField(verbose_name='Date de départ')),
                ('guests', models.IntegerField(default=1, verbose_name='Nombre de convives')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (€)')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Demandes particulières')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
